name: Playwright Tests

on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]

jobs:
  test:
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for widget builder to be deployed
        uses: SFDigitalServices/wait-for-deployment-action@v1
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Preview - widget-builder 

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: Install virtual display
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb          

      - name: Run Playwright tests
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
          pnpm playwright test
        env:
          BASE_URL: ${{ steps.deployment.outputs.url }}
          CURRENTS_PROJECT_ID: ${{ secrets.WIDGET_CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
          CURRENTS_CI_BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}
          DISPLAY: :0.0
          CI: true