name: Playwright Tests

on:
  deployment_status:

jobs:
  test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – widget-builder'
    timeout-minutes: 60
    defaults:
      run:
        working-directory: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: Install virtual display
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb          
          
        # https://playwright.dev/docs/next/ci#running-headed  
      - name: Run Playwright tests
        run: xvfb-run pnpm playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          CURRENTS_PROJECT_ID: ${{ secrets.WIDGET_CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
          CURRENTS_CI_BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}
          WIDGET_WALLET_PRIVATE_KEY: ${{ secrets.WIDGET_WALLET_PRIVATE_KEY}}
          CI: true